### PR TITLE
Xamarin.Forms 5 project added

### PR DESCRIPTION
**Pull request by roubachof**

### CODE REVIEW

**Comment by roubachof** [comment]
@jonathanpeppers I think you might want to refresh the others screenshots with the Thread.Sleep(4) :)

**Comment by roubachof** [comment]
xf
maui
 cause I don't have the same results on an old galaxy A5 (2017)

**Comment by roubachof** [comment]
On the emulator however, with Thread.Sleep(2), maui and XF have same perf:

lols-maui
lols-xf5

**Comment by jonathanpeppers** [comment]
I tested mine on a Release build on a Pixel 5 device. Same as the other screenshots I have.

**Pull request merged**
